#!name=毒奶特供（09.15.2023更新）
#!desc=毒奶去网页广告计划（稳定版）For Surge / Quantumult X / Shadowrocket/ 油猴 - Tampermonkey ；如去内容农场/泥巴影视/低端影视/哔滴影视/Jable/Missav/Pornhub/91../禁漫天堂/百度与谷歌搜索结果页面广告/片库网/Gimy剧迷网等视频网站广告或其他ACG网站网页广告/百度知道广告；
#!重写配置最后更新于 09.15.2023；
#!讨论组 https://t.me/Adblock4limbo ；
#!毒奶博客 https://limbopro.com；
#!仅供个人及极小部分QX/Surge/Shadowrocket用户使用；
#!可在 QX/Surge/Shadowrocket - MitM - 添加主机名 处，通过添加主机名的方法排除掉不想去广告的域名；(如 -google.com)

[URL Rewrite]
# missav 播放页弹窗
https?:\/\/[0-9a-zA-Z]{10,16}\.cloudfront\.net\/\?[a-z]{3,7}=\d{4,8} reject

# Avple 弹窗跳转
^https?:\/\/assert\.avple\.tv\/file\/avple-images\/ad\.js reject

# Pornhub 视频广告
^https:\/\/(cn|www)\.pornhub\.com\/_xa\/ads.* reject

# 91Porn 视频广告
^https:\/\/(img|vthumb)\.killcovid2021\.com.*?\.mp4 reject

# Pornhub 跳转
(^https?:\/\/www\.pornhub\.com)(.*) https://cn.pornhub.com$2 307

# Xvideos JS abort
^https:\/\/.*\/js\/static\/header\/sda\/ppsuma*.js reject
^https:\/\/www.xvideos.com/zoneload.* reject

# javmost 播放页弹窗广告
^https:\/\/suzihaza\.com\/asset\/jquery\/slim-3\.2\.min\.js.* reject

# 百度网页跳转至手机网页版本
# www.baidu.com(?!(.*(cdn-cgi|\.))).* m.baidu.com 302

# 禁知乎网页广告
https://(www|zhuanlan)\.zhihu\.com/api/v4/questions/\d+/related-readings reject
https://(www|zhuanlan)\.zhihu\.com/api/v4/answers/\d+/related-readings reject
#https://(www|zhuanlan)\.zhihu\.com/api/v4/hot_recommendation reject
https://(www|zhuanlan)\.zhihu\.com/commercial_api/banners_v3/(mobile_banner|mobile_question) reject
https://(www|zhuanlan)\.zhihu\.com/api/articles/\d+/recommendation reject

# missav 直播跳出广告
https://creative.live.missav.com/widgets/Spot/lib.js reject

[Header Rewrite]
^https?:\/\/(www\.xvideos)(\.)(\w{0,3})(?!(.*(api|cdn-cgi|\.))).* header-replace Content-Security-Policy *

[Script]

小宝影视(xiaobaotv.net) = type=http-response , script-path=https://limbopro.com/Adguard/Adblock4limbo.js , pattern=^https?:\/\/(xiaobaotv\.(net|com))\/(?!(.*(cdn-cgi|\.))).* , max-size=-1 , requires-body=true , timeout=10 , script-update-interval=0 , enable=true
91short(cn1.91short.com) = type=http-response , script-path=https://limbopro.com/Adguard/Adblock4limbo.js , pattern=^https?:\/\/(cn1|www)\.(91short\.com)\/(?!(.*(cdn-cgi|\.))).* , max-size=-1 , requires-body=true , timeout=10 , script-update-interval=0 , enable=true
泥巴影视(Nivod4.tv) = type=http-response , script-path=https://limbopro.com/Adguard/Adblock4limbo.js , pattern=^https?:\/\/(www|m)\.(nivod4\.tv)\/(?!(.*(cdn-cgi|\.))).* , max-size=-1 , requires-body=true , timeout=10 , script-update-interval=0 , enable=true
知道搜索广告(zhidao.baidu.com) = type=http-response , script-path=https://raw.githubusercontent.com/limbopro/Adblock4limbo/main/Adguard/surge_baidu.zhidao.js , pattern=^https?:\/\/(zhidao)\.baidu\.com\/(question|index|\?fr|\?word) , max-size=-1 , requires-body=true , timeout=10 , script-update-interval=0 , enable=true
搜索首页广告(www.baidu.com) = type=http-response , script-path=https://limbopro.com/Adguard/surge_baidu.index.js , pattern=^https?:\/\/(www|m)\.baidu\.com(/$|\/\?ref.*)(?!(.*(cdn-cgi|\.))).* , max-size=-1 , requires-body=true , timeout=10 , script-update-interval=0 , enable=true
搜索结果广告(www.baidu.com) = type=http-response , script-path=https://limbopro.com/Adguard/surge_baidu.js , pattern=^https?:\/\/(www|m)\.baidu\.com(\/s\?word.*|\/from.*?\/s\?word.*|\/from.*?word=.*) , max-size=-1 , requires-body=true , timeout=10 , script-update-interval=0 , enable=true
内容农场(www.bing.com) = type=http-response , script-path=https://limbopro.com/Adguard/Adblock4limbo.js , pattern=^https?:\/\/(www\.bing)(\.\w{2,4}){1,2}\/(search\?.*|\?sa=|\?FORM)(?!.*?(apps=)) , max-size=0 , requires-body=true , timeout=10 , script-update-interval=0 , enable=true
内容农场(www.google.com|com.hk) = type=http-response , script-path=https://limbopro.com/Adguard/Adblock4limbo.js , pattern=^https?:\/\/(www\.google)(\.\w{2,4}){1,2}\/(search\?|\?sa=|\?FORM)(?!.*?(apps=)) , max-size=0 , requires-body=true , timeout=10 , script-update-interval=0 , enable=true
禁漫天堂(18comic.org|vip) = type=http-response , script-path=https://limbopro.com/Adguard/Adblock4limbo.js , pattern=^https?:\/\/18comic\.(vip|org)\/(?!(.*(onclick|cdn-cgi|\.))).* , max-size=0 , requires-body=true , timeout=10 , script-update-interval=0 , enable=true
紳士漫畫(www.wnacg.com) = type=http-response , script-path=https://limbopro.com/Adguard/Adblock4limbo.js , pattern=^https?:\/\/www\.wnacg\.com\/(?!(.*(onclick|cdn-cgi|\.))).* , max-size=0 , requires-body=true , timeout=10 , script-update-interval=0 , enable=true
剧迷网(gimy.app|ai) = type=http-response , script-path=https://raw.githubusercontent.com/limbopro/Adblock4limbo/main/Adguard/surge_gimy.js , pattern=^https?:\/\/(\w{0,3}(\.){0,1}(gimy)(\.)\w{0,3})\/(?!(.*(cdn-cgi|\.))).* , max-size=0 , requires-body=true , timeout=10 , script-update-interval=0 , enable=true
低端影视(ddrk.me|ddys.pro) = type=http-response , script-path=https://limbopro.com/Adguard/Adblock4limbo.js , pattern=^https?:\/\/(ddys|ddrk|ddys2)\.\w{0,3}\/(?!(.*(cdn-cgi|getvddr|\=json|\.))).* , max-size=0 , requires-body=true , timeout=10 , script-update-interval=0 , enable=true
哔嘀影视播放页(www.btbdys.com) = type=http-response , script-path=https://limbopro.com/Adguard/Adblock4limbo.js , pattern=^https?:\/\/www\.(btbdys|bdys(01|02|03|10))\.com\/play\/.*?\.htm.* , max-size=0 , requires-body=true , timeout=10 , script-update-interval=0 , enable=true
哔嘀影视展示页(www.btbdys.com) = type=http-response , script-path=https://limbopro.com/Adguard/Adblock4limbo.js , pattern=^https?:\/\/www\.(btbdys|bdys(01|02|03|10))\.com\/(?!(.*(verifyCode|member|zzzzz|cdn-cgi|\.))).* , max-size=0 , requires-body=true , timeout=10 , script-update-interval=0 , enable=true
独播库(www.duboku.tv) = type=http-response , script-path=https://raw.githubusercontent.com/limbopro/Adblock4limbo/main/Adguard/surge_duboku.js , pattern=^https?:\/\/www\.duboku\.tv\/(?!(.*(cdn-cgi|\.))).* , max-size=0 , requires-body=true , timeout=10 , script-update-interval=0 , enable=true
韩剧TV(www.tvn.cc) = type=http-response , script-path=https://limbopro.com/Adguard/Adblock4limbo.js , pattern=^https?:\/\/www\.tvn\.cc\/(?!(.*(cdn-cgi|\.))).* , max-size=0 , requires-body=true , timeout=10 , script-update-interval=0 , enable=true
555电影网(555dy.com)P.S.鉴于域名经常跳转将不再维护 = type=http-response , script-path=https://limbopro.com/Adguard/Adblock4limbo.js , pattern=^https?:\/\/(555dy\w{0,3})\.(com|top|shop)\/(?!(.*(cdn-cgi|\.))).* , max-size=0 , requires-body=true , timeout=10 , script-update-interval=0 , enable=true
梨播(libvio.top) = type=http-response , script-path=https://raw.githubusercontent.com/limbopro/Adblock4limbo/main/Adguard/surge_libvio.js , pattern=^https?:\/\/libvio\.top\/(?!(.*(cdn-cgi|\.))).* , max-size=0 , requires-body=true , timeout=10 , script-update-interval=0 , enable=true
Netflav(netflav.com) = type=http-response , script-path=https://raw.githubusercontent.com/limbopro/Adblock4limbo/main/Adguard/surge_netflav.js , pattern=^https?:\/\/netflav\.com\/(?!(.*(cdn-cgi|\.))).* , max-size=0 , requires-body=true , timeout=10 , script-update-interval=0 , enable=true
Javmost(javmost.xyz) = type=http-response , script-path=https://raw.githubusercontent.com/limbopro/Adblock4limbo/main/Adguard/surge_javmost.js , pattern=^https?:\/\/\w{3,5}\.javmost\.com\/(?!(.*(cdn-cgi|\.))).* , max-size=0 , requires-body=true , timeout=10 , script-update-interval=0 , enable=true
Javbus(www.javbus.com) = type=http-response , script-path=https://raw.githubusercontent.com/limbopro/Adblock4limbo/main/Adguard/surge_javbus.js , pattern=^https?:\/\/www\.javbus\.com\/(?!(.*(cdn-cgi|\.))).* , max-size=0 , requires-body=true , timeout=10 , script-update-interval=0 , enable=true
Avple(avple.tv) = type=http-response , script-path=https://limbopro.com/Adguard/Adblock4limbo.js , pattern=^https?:\/\/avple\.tv\/(?!(.*(cdn-cgi|\.))).* , max-size=0 , requires-body=true , timeout=10 , script-update-interval=0 , enable=true
Jable(jable.tv) = type=http-response , script-path=https://limbopro.com/Adguard/Adblock4limbo.js , pattern=^https?:\/\/jable\.tv\/(?!(.*(\?mode|cdn-cgi|\.))).* , max-size=0 , requires-body=true , timeout=10 , script-update-interval=0 , enable=true
Missav(missav.com) = type=http-response , script-path=https://limbopro.com/Adguard/Adblock4limbo.js , pattern=^https?:\/\/missav\.com\/(?!(.*(api|cdn-cgi|\.))).* , max-size=0 , requires-body=true , timeout=10 , script-update-interval=0 , enable=true
Javday(javday.tv) = type=http-response , script-path=https://limbopro.com/Adguard/Adblock4limbo.js , pattern=^https?:\/\/javday\.tv\/(?!(.*(api|cdn-cgi|\.))).* , max-size=0 , requires-body=true , timeout=10 , script-update-interval=0 , enable=true
Xvideos(www.xvideos.com) = type=http-response , script-path=https://limbopro.com/Adguard/Adblock4limbo.js , pattern=^https?:\/\/www\.xvideos\.com\/(?!(.*(api|cdn-cgi|\.))).* , max-size=0 , requires-body=true , timeout=10 , script-update-interval=0 , enable=true
4hu(4hu.tv) = type=http-response , script-path=https://raw.githubusercontent.com/limbopro/Adblock4limbo/main/Adguard/surge_4hu.js , pattern=^https?:\/\/4hu\.tv\/(?!(.*(cdn-cgi|\.))).* , max-size=0 , requires-body=true , timeout=10 , script-update-interval=0 , enable=true
Pornhub(cn.pornhub.com) = type=http-response , script-path=https://limbopro.com/Adguard/Adblock4limbo.js , pattern=^https?:\/\/(\w{0,3}(\.){0,1}(pornhub)(\.)\w{0,3})\/(?!(.*(cdn-cgi|(\.(js|jpeg|png|gif|zip|js|woff|woff2|css|m3u8))))).* , max-size=0 , requires-body=true , timeout=10 , script-update-interval=0 , enable=true
91porn(www.91porn.com) = type=http-response , script-path=https://limbopro.com/Adguard/Adblock4limbo.js , pattern=^https?:\/\/\w{0,3}(\.){0,1}91porn\.com\/(?!(.*(cdn-cgi|(\.(js|jpeg|png|gif|zip|js|woff|woff2|css|m3u8))))).* , max-size=0 , requires-body=true , timeout=10 , script-update-interval=0 , enable=true
ttsp(www.ttsp.tv) = type=http-response , script-path=https://limbopro.com/Adguard/Adblock4limbo.js , pattern=^https?:\/\/(www.ttsp.tv)\/(?!(.*(cdn-cgi|\.))).* , max-size=0 , requires-body=true , timeout=10 , script-update-interval=0 , enable=true
tz659(www.tz659.com) = type=http-response , script-path=https://limbopro.com/Adguard/Adblock4limbo.js , pattern=^http?:\/\/www\.tz659\.com\/(?!(.*(cdn-cgi|\.))).* , max-size=0 , requires-body=true , timeout=10 , script-update-interval=0 , enable=true
anime1(anime1.me) = type=http-response , script-path=https://limbopro.com/Adguard/Adblock4limbo.js , pattern=^https?:\/\/anime1\.me\/(?!(.*(cdn-cgi|\.))).* , max-size=0 , requires-body=true , timeout=10 , script-update-interval=0 , enable=true
yhdmp(m.yhdmp.com) = type=http-response , script-path=https://limbopro.com/Adguard/Adblock4limbo.js , pattern=^https?:\/\/m\.yhpdm\.com\/(?!(.*(cdn-cgi|\.))).* , max-size=0 , requires-body=true , timeout=10 , script-update-interval=0 , enable=true

[MITM]
hostname = %APPEND% static-cdn77.xvideos-cdn.com, www.xvideos.com, javday.tv, xiaobaotv.net, cn1.91short.com, vthumb.killcovid2021.com, img.killcovid2021.com, m.nivod4.tv, www.nivod4.tv, m.yhpdm.com, m.yhdmp.cc, m.yhdmp.com, anime1.me, www.tz659.com, www.ttsp.tv, *.cloudfront.net, www.o8tv.com, www.555dd*.com, www.5dy*, *.tvn.cc, www.wnacg.com, www.wnacg.org, suzihaza.com, 91porn.com, netflav.com, www.javmost.xyz, javmost.xyz, www5.javmost.xyz, www5.javmost.com, www.bing.com, zhuanlan.zhihu.com, www.zhihu.com, jable.tv, *.tvn.cc, ddrk.me, ddys.pro, ddys.tv, ddys.art, ddys2.me, 18comic.org, 18comic.vip, www.google.com, www.google.com.hk, www.pornhub.com, cn.pornhub.com, missav.com, www.libvio.com, www.libvio.la, 4hu.*, gimy.ai, gimy.tv, *.duboku.*, assert.avple.tv, avple.tv, *.btbdys.*, www.bdys01.com, www.bdys02.com, www.bdys03.com, www.bdys10.com, *.javbus.*, www.baidu.com, m.baidu.com, zhidao.baidu.com
